apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: demo
  labels:
    app: nginx-frontend
    version: v1
    app.kubernetes.io/name: nginx-frontend
    app.kubernetes.io/instance: nginx-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: nginx-demo
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-frontend
      version: v1
  template:
    metadata:
      labels:
        app: nginx-frontend
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-frontend-config
      - name: html-content
        configMap:
          name: nginx-frontend-html
