apiVersion: v1
kind: ServiceMonitor
metadata:
  name: nginx-services
  namespace: demo
  labels:
    app.kubernetes.io/name: nginx-monitoring
    app.kubernetes.io/part-of: nginx-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: nginx-demo
  endpoints:
  - port: http
    path: /health
    interval: 30s
    honorLabels: true
---
apiVersion: networking.istio.io/v1beta1
kind: Telemetry
metadata:
  name: nginx-metrics
  namespace: demo
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        destination_service_name:
          value: "%{DESTINATION_SERVICE_NAME | 'unknown'}"
        source_app:
          value: "%{SOURCE_APP | 'unknown'}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-nginx
  namespace: demo
  labels:
    grafana_dashboard: "1"
data:
  nginx-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Nginx Services Dashboard",
        "tags": ["nginx", "istio"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(istio_requests_total{destination_service_name=~\"nginx-.*\"}[5m])) by (destination_service_name)",
                "legendFormat": "{{destination_service_name}}"
              }
            ],
            "xAxis": {"show": true},
            "yAxes": [{"label": "Requests/sec", "show": true}],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Response Times",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"nginx-.*\"}[5m])) by (destination_service_name, le))",
                "legendFormat": "95th percentile - {{destination_service_name}}"
              }
            ],
            "xAxis": {"show": true},
            "yAxes": [{"label": "Duration (ms)", "show": true}],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "refresh": "5s"
      }
    }
