apiVersion: v1
kind: Service
metadata:
  name: nginx-api
  namespace: demo
  labels:
    app: nginx-api
    service: nginx-api
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-api
