apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-frontend-vs
  namespace: demo
spec:
  hosts:
  - nginx-frontend.local
  gateways:
  - nginx-gateway
  http:
  # Header-based routing: Route traffic with version=v2 header to v2
  - match:
    - headers:
        version:
          exact: v2
    route:
    - destination:
        host: nginx-frontend
        subset: v2
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
  # Path-based routing: Route /v2 and /beta paths to v2
  - match:
    - uri:
        prefix: /v2
    route:
    - destination:
        host: nginx-frontend
        subset: v2
        port:
          number: 80
  - match:
    - uri:
        prefix: /beta
    route:
    - destination:
        host: nginx-frontend
        subset: v2
        port:
          number: 80
  # Weight-based routing: Split remaining traffic 80% v1, 20% v2
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-frontend
        subset: v1
        port:
          number: 80
      weight: 80
    - destination:
        host: nginx-frontend
        subset: v2
        port:
          number: 80
      weight: 20
    fault:
      delay:
        percentage:
          value: 0.1
        fixedDelay: 5s
    retries:
      attempts: 3
      perTryTimeout: 2s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-api-vs
  namespace: demo
spec:
  hosts:
  - nginx-api.local
  gateways:
  - nginx-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: nginx-api
        port:
          number: 80
    timeout: 10s
    retries:
      attempts: 2
      perTryTimeout: 5s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-api
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-admin-vs
  namespace: demo
spec:
  hosts:
  - nginx-admin.local
  gateways:
  - nginx-gateway
  http:
  - match:
    - uri:
        prefix: /admin
    route:
    - destination:
        host: nginx-admin
        port:
          number: 80
    timeout: 15s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-admin
        port:
          number: 80
