apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend-v2
  namespace: demo
  labels:
    app: nginx-frontend
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-frontend
      version: v2
  template:
    metadata:
      labels:
        app: nginx-frontend
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-frontend-v2-config
      - name: html-content
        configMap:
          name: nginx-frontend-v2-html
